# Generated by Django 6.0.3 on 2026-03-28 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaPreferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="marketplace.produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alertas_preferencia",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "ativo"],
                        name="alertas_pre_usuario_51b995_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("create", "Criar"),
                            ("update", "Atualizar"),
                            ("delete", "Eliminar"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tabela_afetada", models.CharField(max_length=100)),
                ("registro_id", models.IntegerField(blank=True, null=True)),
                ("descricao", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dados_antigos", models.JSONField(blank=True, null=True)),
                ("dados_novos", models.JSONField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "logs_auditoria",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "acao"],
                        name="logs_audito_usuario_3582d1_idx",
                    ),
                    models.Index(
                        fields=["tabela_afetada", "data_criacao"],
                        name="logs_audito_tabela__a43586_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(default="", max_length=200)),
                ("conteudo", models.TextField()),
                ("tipo", models.CharField(default="suporte", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("respondido", "Respondido"),
                            ("fechado", "Fechado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("resposta", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens_respondidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mensagens",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "status"],
                        name="mensagens_usuario_fb47b0_idx",
                    ),
                    models.Index(
                        fields=["data_criacao"], name="mensagens_data_cr_2b6faf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("aviso", "Aviso"),
                            ("erro", "Erro"),
                            ("sucesso", "Sucesso"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notificacoes",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "lida"],
                        name="notificacoe_usuario_56e4b8_idx",
                    ),
                    models.Index(
                        fields=["data_criacao"], name="notificacoe_data_cr_c2b9c3_idx"
                    ),
                ],
            },
        ),
    ]
