# Generated by Django 5.0.3 on 2026-03-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoContato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(help_text="Ex: +244923456789", max_length=20),
                ),
                ("email_suporte", models.EmailField(max_length=254)),
                ("email_comercial", models.EmailField(max_length=254)),
                ("endereco", models.TextField(blank=True, null=True)),
                (
                    "horario_atendimento",
                    models.CharField(
                        default="Segunda a Sexta, 8h às 17h", max_length=200
                    ),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Informações de Contato",
                "verbose_name_plural": "Informações de Contato",
                "db_table": "info_contato",
            },
        ),
        migrations.CreateModel(
            name="PaginaSobre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(default="Sobre a AgroKongo", max_length=200),
                ),
                ("missao", models.TextField()),
                ("visao", models.TextField()),
                (
                    "valores",
                    models.TextField(help_text="Valores separados por vírgula"),
                ),
                ("historia", models.TextField()),
                ("equipa", models.TextField(blank=True, null=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Página Sobre",
                "verbose_name_plural": "Página Sobre",
                "db_table": "pagina_sobre",
            },
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telemovel", models.CharField(blank=True, max_length=20, null=True)),
                ("assunto", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("respondido", "Respondido"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("resposta", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contatos",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
