# Generated by Django 6.0.3 on 2026-03-24 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("categoria", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Safra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "preco_por_unidade",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True, default="disponivel", max_length=20
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "imagem",
                    models.CharField(default="default_safra.webp", max_length=150),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to="marketplace.produto",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Safra",
                "verbose_name_plural": "Safras",
                "db_table": "safras",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fatura_ref",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "quantidade_comprada",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "valor_total_pago",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "comissao_plataforma",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "valor_liquido_vendedor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pendente_pagamento", "Aguardando Pagamento"),
                            ("pagamento_sob_analise", "Em Análise"),
                            ("pago_escrow", "Em Escrow"),
                            ("mercadoria_enviada", "Enviado"),
                            ("mercadoria_entregue", "Entregue"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                            ("em_disputa", "Em Disputa"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=30,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_pagamento_escrow", models.DateTimeField(blank=True, null=True)),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                ("data_entrega", models.DateTimeField(blank=True, null=True)),
                ("data_liquidacao", models.DateTimeField(blank=True, null=True)),
                ("previsao_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "comprovativo_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transferencia_concluida", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "safra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacoes",
                        to="marketplace.safra",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "db_table": "transacoes",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_anterior", models.CharField(max_length=30)),
                ("status_novo", models.CharField(max_length=30)),
                ("data_mudanca", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="marketplace.transacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Status",
                "db_table": "historico_status",
                "ordering": ["-data_mudanca"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.IntegerField()),
                ("comentario", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="marketplace.transacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "db_table": "avaliacoes",
            },
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(
                fields=["produto_id", "status"], name="safras_produto_6cfc4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transacao",
            index=models.Index(
                fields=["status", "deleted_at"], name="transacoes_status_edf3f8_idx"
            ),
        ),
    ]
