# Generated by Django 6.0.3 on 2026-03-28 03:11

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("icone", models.CharField(default="fa-leaf", max_length=50)),
                ("ordem", models.IntegerField(default=0)),
                ("ativa", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "categorias",
                "ordering": ["ordem", "nome"],
                "indexes": [
                    models.Index(fields=["slug"], name="categorias_slug_e69df5_idx"),
                    models.Index(fields=["ativa"], name="categorias_ativa_dafa85_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("kg", "Quilograma (kg)"),
                            ("ton", "Tonelada (ton)"),
                            ("saca", "Saca (50kg)"),
                            ("cx", "Caixa"),
                            ("lt", "Litro (lt)"),
                            ("un", "Unidade"),
                            ("fardo", "Fardo"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                (
                    "preco_referencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço médio de referência",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("imagem", models.CharField(blank=True, max_length=150, null=True)),
                ("ativa", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="marketplace.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente Confirmação"),
                            ("confirmada", "Confirmada"),
                            ("paga", "Paga"),
                            ("cancelada", "Cancelada"),
                            ("concluida", "Concluída"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "fatura_ref",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("data_validacao", models.DateTimeField(blank=True, null=True)),
                ("motivo_rejeicao", models.TextField(blank=True, null=True)),
                ("observacoes_comprador", models.TextField(blank=True, null=True)),
                ("observacoes_vendedor", models.TextField(blank=True, null=True)),
                ("data_reserva", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                (
                    "comprador",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "comprador"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "reservas",
                "ordering": ["-data_reserva"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferência Bancária"),
                            ("deposito", "Depósito Bancário"),
                            ("multicaixa", "Multicaixa"),
                            ("mbanca", "mBanca"),
                            ("iku", "IKU"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        default="transferencia",
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                (
                    "comprovativo",
                    models.FileField(
                        blank=True,
                        help_text="Ficheiro do comprovativo de pagamento (PDF, JPG, PNG)",
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="media/comprovativos"
                        ),
                        upload_to="comprovativos/%Y/%m/%d/",
                    ),
                ),
                (
                    "referencia_bancaria",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente Validação"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_validacao", models.DateTimeField(blank=True, null=True)),
                ("motivo_rejeicao", models.TextField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagamentos_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="marketplace.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "db_table": "pagamentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Safra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("kg", "Quilograma (kg)"),
                            ("ton", "Tonelada (ton)"),
                            ("saca", "Saca (50kg)"),
                            ("cx", "Caixa"),
                            ("lt", "Litro (lt)"),
                            ("un", "Unidade"),
                            ("fardo", "Fardo"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending", "Pendente Aprovação"),
                            ("approved", "Aprovado"),
                            ("active", "Ativo"),
                            ("reserved", "Reservado"),
                            ("sold", "Vendido"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("motivo_rejeicao", models.TextField(blank=True, null=True)),
                (
                    "qualidade",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("padrao", "Padrão"),
                            ("economico", "Económico"),
                        ],
                        default="padrao",
                        max_length=50,
                    ),
                ),
                ("data_colheita", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("certificacao_organica", models.BooleanField(default=False)),
                (
                    "imagem_principal",
                    models.CharField(
                        blank=True,
                        help_text="URL da imagem principal",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "imagem_alta_resolucao",
                    models.CharField(
                        blank=True,
                        help_text="URL da imagem em alta resolução para ZOOM",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "quantidade_reservada",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "quantidade_vendida",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                ("visualizacoes", models.IntegerField(default=0)),
                ("favoritos", models.IntegerField(default=0)),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safras",
                        to="locations.municipio",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to="marketplace.produto",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "produtor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safras",
                        to="locations.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safra",
                "verbose_name_plural": "Safras",
                "db_table": "safras",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="reserva",
            name="safra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="marketplace.safra",
            ),
        ),
        migrations.CreateModel(
            name="ImagemSafra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.CharField(help_text="URL da imagem normal", max_length=150),
                ),
                (
                    "imagem_alta_resolucao",
                    models.CharField(
                        blank=True,
                        help_text="URL da imagem em alta resolução para ZOOM",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("legenda", models.CharField(blank=True, max_length=200, null=True)),
                ("principal", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=0)),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "safra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="marketplace.safra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Safra",
                "verbose_name_plural": "Imagens das Safras",
                "db_table": "imagens_safra",
                "ordering": ["ordem", "-principal"],
            },
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["slug"], name="produtos_slug_571185_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["categoria"], name="produtos_categor_79cde9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["ativa"], name="produtos_ativa_23ce4e_idx"),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(
                fields=["reserva"], name="pagamentos_reserva_d48506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(fields=["status"], name="pagamentos_status_df81aa_idx"),
        ),
        migrations.AddIndex(
            model_name="pagamento",
            index=models.Index(fields=["metodo"], name="pagamentos_metodo_e30ae4_idx"),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(fields=["produtor"], name="safras_produto_ae906b_idx"),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(fields=["produto"], name="safras_produto_53afcb_idx"),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(fields=["status"], name="safras_status_b84495_idx"),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(fields=["provincia"], name="safras_provinc_e09735_idx"),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(
                fields=["preco_unitario"], name="safras_preco_u_2fcfdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safra",
            index=models.Index(
                fields=["data_criacao"], name="safras_data_cr_6509fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(fields=["safra"], name="reservas_safra_i_75b430_idx"),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["comprador"], name="reservas_comprad_1f97a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(fields=["status"], name="reservas_status_4ca917_idx"),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["fatura_ref"], name="reservas_fatura__4c3b54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagemsafra",
            index=models.Index(fields=["safra"], name="imagens_saf_safra_i_f7b811_idx"),
        ),
        migrations.AddIndex(
            model_name="imagemsafra",
            index=models.Index(
                fields=["principal"], name="imagens_saf_princip_d1ec5a_idx"
            ),
        ),
    ]
