# Generated by Django 5.0.3 on 2026-03-30 21:08

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={},
        ),
        migrations.AlterModelOptions(
            name="imagemsafra",
            options={"ordering": ["ordem", "-principal"]},
        ),
        migrations.AlterModelOptions(
            name="pagamento",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={"ordering": ["-data_reserva"]},
        ),
        migrations.AlterModelOptions(
            name="safra",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="categoria",
            name="categorias_slug_e69df5_idx",
        ),
        migrations.RemoveIndex(
            model_name="categoria",
            name="categorias_ativa_dafa85_idx",
        ),
        migrations.RemoveIndex(
            model_name="imagemsafra",
            name="imagens_saf_safra_i_f7b811_idx",
        ),
        migrations.RemoveIndex(
            model_name="imagemsafra",
            name="imagens_saf_princip_d1ec5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagamento",
            name="pagamentos_reserva_d48506_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagamento",
            name="pagamentos_status_df81aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagamento",
            name="pagamentos_metodo_e30ae4_idx",
        ),
        migrations.RemoveIndex(
            model_name="produto",
            name="produtos_slug_571185_idx",
        ),
        migrations.RemoveIndex(
            model_name="produto",
            name="produtos_categor_79cde9_idx",
        ),
        migrations.RemoveIndex(
            model_name="produto",
            name="produtos_ativa_23ce4e_idx",
        ),
        migrations.RemoveIndex(
            model_name="reserva",
            name="reservas_safra_i_75b430_idx",
        ),
        migrations.RemoveIndex(
            model_name="reserva",
            name="reservas_comprad_1f97a9_idx",
        ),
        migrations.RemoveIndex(
            model_name="reserva",
            name="reservas_status_4ca917_idx",
        ),
        migrations.RemoveIndex(
            model_name="reserva",
            name="reservas_fatura__4c3b54_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_produto_ae906b_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_produto_53afcb_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_status_b84495_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_provinc_e09735_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_preco_u_2fcfdf_idx",
        ),
        migrations.RemoveIndex(
            model_name="safra",
            name="safras_data_cr_6509fc_idx",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="icone",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="ordem",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="safra",
            name="imagem_alta_resolucao",
        ),
        migrations.RemoveField(
            model_name="safra",
            name="motivo_rejeicao",
        ),
        migrations.RemoveField(
            model_name="safra",
            name="preco_total",
        ),
        migrations.AddField(
            model_name="reserva",
            name="comissao_plataforma",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="reserva",
            name="unidade_medida",
            field=models.CharField(default="kg", max_length=20),
        ),
        migrations.AddField(
            model_name="reserva",
            name="valor_liquido_vendedor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="imagemsafra",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="safras/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="imagemsafra",
            name="imagem_alta_resolucao",
            field=models.ImageField(
                blank=True, null=True, upload_to="safras/hd/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="comprovativo",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/comprovativos"
                ),
                upload_to="comprovativos/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    marketplace.models.validate_file_mime,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("transferencia", "Transferência Bancária"),
                    ("multicaixa", "Multicaixa"),
                    ("deposito", "Depósito"),
                ],
                default="transferencia",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos_validados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_referencia",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(default="kg", max_length=20),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="comprador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="preco_total",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("confirmada", "Confirmada"),
                    ("paga", "Paga"),
                    ("recebida", "Recebida"),
                    ("em_disputa", "Em Disputa"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                    ("reembolsada", "Reembolsada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas_validadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="safra",
            name="imagem_principal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="safra",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="safra",
            name="produtor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="safra",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="safra",
            name="qualidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="safra",
            name="quantidade_reservada",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="safra",
            name="quantidade_vendida",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="safra",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativa"),
                    ("sold", "Esgotada"),
                    ("cancelled", "Cancelada"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="safra",
            name="unidade_medida",
            field=models.CharField(default="kg", max_length=20),
        ),
    ]
