# Generated by Django 6.0.3 on 2026-03-28 03:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("produtor", "Produtor"),
                            ("comprador", "Comprador"),
                        ],
                        help_text="Tipo principal: admin, produtor ou comprador",
                        max_length=20,
                    ),
                ),
                (
                    "subtipo",
                    models.CharField(
                        blank=True,
                        help_text="Sub-tipo específico (ex: fazenda, restaurante, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        help_text="NIF pessoal ou da empresa (9 dígitos)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "telemovel",
                    models.CharField(
                        help_text="Telemóvel angolano (9xxxxxxxx)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        help_text="Data de nascimento (pessoa física)",
                        null=True,
                    ),
                ),
                (
                    "nome_empresa",
                    models.CharField(
                        blank=True,
                        help_text="Nome legal da empresa",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True,
                        help_text="Nome comercial/fantasia",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "documento_empresa",
                    models.CharField(
                        blank=True,
                        help_text="NIF da empresa ou documento equivalente",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "alvara_comercial",
                    models.CharField(
                        blank=True,
                        help_text="Número do alvará comercial",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="IBAN para recebimentos (AO06...)",
                        max_length=34,
                        null=True,
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, help_text="Nome do banco", max_length=100, null=True
                    ),
                ),
                (
                    "numero_registo_cooperativa",
                    models.CharField(
                        blank=True,
                        help_text="Número de registo da cooperativa",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "data_fundacao",
                    models.DateField(
                        blank=True,
                        help_text="Data de fundação da empresa/cooperativa",
                        null=True,
                    ),
                ),
                (
                    "tipo_producao",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de produção (ex: milho, café, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "certificacao_organica",
                    models.BooleanField(
                        default=False, help_text="Possui certificação orgânica?"
                    ),
                ),
                (
                    "rating_vendedor",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Avaliação média (0-5)",
                        max_digits=3,
                    ),
                ),
                (
                    "vendas_concluidas",
                    models.IntegerField(
                        default=0, help_text="Total de vendas concluídas"
                    ),
                ),
                (
                    "compras_realizadas",
                    models.IntegerField(
                        default=0, help_text="Total de compras realizadas"
                    ),
                ),
                (
                    "foto_perfil",
                    models.CharField(
                        default="default_user.svg",
                        help_text="URL da foto de perfil",
                        max_length=150,
                    ),
                ),
                (
                    "foto_documento",
                    models.CharField(
                        blank=True,
                        help_text="URL da foto do documento",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "documento_pdf",
                    models.CharField(
                        blank=True,
                        help_text="URL do documento em PDF",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "perfil_completo",
                    models.BooleanField(
                        default=False, help_text="Perfil completo (KYC validado)?"
                    ),
                ),
                (
                    "conta_validada",
                    models.BooleanField(
                        default=False, help_text="Conta validada por admin?"
                    ),
                ),
                (
                    "validacao_documento",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        help_text="Status da validação de documentos",
                        max_length=20,
                    ),
                ),
                (
                    "endereco_completo",
                    models.TextField(
                        blank=True, help_text="Endereço completo", null=True
                    ),
                ),
                (
                    "saldo_disponivel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Saldo disponível na carteira",
                        max_digits=14,
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, help_text="Data de última atualização"
                    ),
                ),
                (
                    "ultimo_login",
                    models.DateTimeField(
                        blank=True, help_text="Data do último login", null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Município de residência/sede",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="locations.municipio",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Província de residência/sede",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="locations.provincia",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "usuarios",
                "indexes": [
                    models.Index(
                        fields=["telemovel"], name="usuarios_telemov_cb59a4_idx"
                    ),
                    models.Index(fields=["email"], name="usuarios_email_0ff7b3_idx"),
                    models.Index(fields=["tipo"], name="usuarios_tipo_02599b_idx"),
                    models.Index(
                        fields=["subtipo"], name="usuarios_subtipo_d2b4ac_idx"
                    ),
                    models.Index(
                        fields=["conta_validada"], name="usuarios_conta_v_990c70_idx"
                    ),
                    models.Index(
                        fields=["tipo", "subtipo"], name="usuarios_tipo_f62a0a_idx"
                    ),
                    models.Index(
                        fields=["validacao_documento"],
                        name="usuarios_validac_edf897_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
