# Generated by Django 5.0.3 on 2026-03-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Levantamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processado", "Processado"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("iban_destino", models.CharField(max_length=34)),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                ("data_processamento", models.DateTimeField(blank=True, null=True)),
                (
                    "comprovativo_transferencia",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "levantamentos",
                "ordering": ["-data_pedido"],
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_telemov_cb59a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_email_0ff7b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_tipo_02599b_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_subtipo_d2b4ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_conta_v_990c70_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_tipo_f62a0a_idx",
        ),
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_validac_edf897_idx",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="alvara_comercial",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="certificacao_organica",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="compras_realizadas",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_fundacao",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="documento_empresa",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="documento_pdf",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="endereco_completo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="foto_documento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome_empresa",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome_fantasia",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="numero_registo_cooperativa",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="rating_vendedor",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="tipo_producao",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="ultimo_login",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="validacao_documento",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="banco",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="conta_validada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto_perfil",
            field=models.CharField(default="default_user.svg", max_length=150),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="iban",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nif",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="perfil_completo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="saldo_disponivel",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="subtipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telemovel",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("produtor", "Produtor"),
                    ("comprador", "Comprador"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="vendas_concluidas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="levantamento",
            name="processado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="levantamentos_processados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="levantamento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levantamentos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
