"""adicionar saldo ao usuario

Revision ID: 7a474bd9890e
Revises: 6ffe380dbcab
Create Date: 2026-02-05 02:10:57.567066

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a474bd9890e"
down_revision = "6ffe380dbcab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "saldo_disponivel", sa.Numeric(precision=14, scale=2), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_column("saldo_disponivel")

    # ### end Alembic commands ###
